import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {Providers} from "@/shared/config/Providers";
import Navbar from "@/shared/ui/Navbar";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const navMenuItems: NavBarMenuItem[] = [
    { label: 'Home', path: '/' },
    { label: 'About', path: '/about' },
    { label: 'Services', path: '/services' },
    { label: 'Contact', path: '/contact' },
];
export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
    <html lang="en" className="h-full bg-white">
    <body className={inter.className + " " + "min-h-full"} >
    <Navbar menuItems={navMenuItems}/>
<Providers>
    {children}
</Providers>
</body>
</html>
)
}
