import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {Providers} from "@/shared/config/Providers";
import Navbar from "@/shared/ui/Navbar";
import {RoutePaths} from "@/shared/const/RoutePaths";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const navMenuItems: NavBarMenuItem[] = [
    { label: 'Home', path: RoutePaths.MAIN},
    { label: 'About', path: RoutePaths.ABOUT },
    { label: 'Services', path: RoutePaths.SERVICES },
    { label: 'Contact', path: RoutePaths.CONTACT},
    { label: 'For business', path: RoutePaths.FOR_BUSINESS },
];
export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    // const headersList = headers();
    // const domain = headersList.get('host') || "";
    // const fullUrl = headersList.get('referer') || "";

    // const headersList = headers();
    // const fullUrl = headersList.get('referer') || "";
    // const url = new URL(fullUrl);
    // const pathname = url.pathname;
    //
    // console.log(pathname);



    return (
    <html lang="en" className="h-full bg-white">
    <body className={inter.className + " " + "min-h-full"} >
    <Navbar menuItems={navMenuItems}/>
<Providers>
    {children}
</Providers>
</body>
</html>
)
}
