import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Navbar from "@/shared/ui/Navbar";
import {headers} from "next/headers";
// import {usePathname} from "next/navigation";


const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

// const navMenuItems: NavBarMenuItem[] = [
//     { label: 'Home', path: '/' },
//     { label: 'About', path: '/about' },
//     { label: 'Services', path: '/services' },
//     { label: 'Contact', path: '/contact' },
// ];
export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    return (
        <>
            {/*<div>lol</div>*/}
            {/*<Navbar menuItems={navMenuItems}/>*/}

            {children}
        </>
    )
}